/**
 * Fallback sample data. Used ONLY when vendors.db is unavailable
 * (e.g. a fresh checkout or a deployment before Supabase is connected),
 * so every page still renders realistically.
 */
import type { VendorRow } from "./vendors";

const j = JSON.stringify;

export const MOCK_VENDORS: VendorRow[] = [
  {
    id: 1,
    company_name: "Meridian Steel Fabrication",
    website_url: "https://meridiansteelfab.example.com",
    city: "Houston",
    state_province: "TX",
    country: "United States",
    headquarters_location: "Houston, TX",
    primary_business_type: "Structural Metal Fabricator",
    company_description:
      "AISC-certified structural steel fabricator serving energy and commercial construction across the Gulf Coast.",
    ai_summary:
      "Meridian Steel Fabrication is an AISC-certified structural fabricator with a 240,000 sq ft facility in Houston, specializing in heavy structural steel for petrochemical, power, and commercial projects. Capabilities include CNC beam lines, robotic welding, and full PEMB packages, with documented capacity of 2,500 tons/month.",
    services: j(["Structural steel fabrication", "Plate processing", "Field erection support"]),
    capabilities: j(["CNC beam line", "Robotic welding", "Blast & prime finishing"]),
    certifications_held: j(["AISC Certified Fabricator", "AWS D1.1", "ISO 9001:2015"]),
    industries_served: j(["Petrochemical", "Power generation", "Commercial construction"]),
    equipment_list: j(["Peddinghaus BDL-1250", "Lincoln PowerWave R450 cells"]),
    contact_email: "quotes@meridiansteelfab.example.com",
    contact_phone: "(713) 555-0142",
    year_established: "1987",
    employee_count: "180",
    facility_size_sqft: "240000",
    logo_url: null,
    enterprise_tier: 1,
    enterprise_suitability_score: 92,
    completeness_status: "verified",
    confidence_level: "high",
    lifecycle_stage: "fully_built",
    data_source: "ThomasNet+AISC",
    last_updated: "2026-07-01 12:00:00",
  },
  {
    id: 2,
    company_name: "Cascade Precision Machining",
    website_url: "https://cascadeprecision.example.com",
    city: "Portland",
    state_province: "OR",
    country: "United States",
    headquarters_location: "Portland, OR",
    primary_business_type: "Precision Machine Shop",
    company_description:
      "5-axis CNC machining for aerospace and semiconductor equipment, AS9100D registered.",
    ai_summary:
      "Cascade Precision Machining operates 22 CNC centers including five 5-axis mills, serving aerospace primes and semiconductor OEMs. AS9100D and ITAR registered with in-house CMM inspection to ±0.0001 in.",
    services: j(["5-axis CNC milling", "CNC turning", "CMM inspection"]),
    capabilities: j(["Titanium machining", "Inconel machining", "Lights-out production"]),
    certifications_held: j(["AS9100D", "ISO 9001:2015", "ITAR Registered"]),
    industries_served: j(["Aerospace", "Semiconductor", "Defense"]),
    equipment_list: j(["DMG MORI DMU 65", "Zeiss Contura CMM"]),
    contact_email: "rfq@cascadeprecision.example.com",
    contact_phone: "(503) 555-0177",
    year_established: "2002",
    employee_count: "64",
    facility_size_sqft: "48000",
    logo_url: null,
    enterprise_tier: 1,
    enterprise_suitability_score: 88,
    completeness_status: "verified",
    confidence_level: "high",
    lifecycle_stage: "fully_built",
    data_source: "IQS+EPA_ECHO",
    last_updated: "2026-06-28 09:30:00",
  },
  {
    id: 3,
    company_name: "Great Lakes Pressure Vessels",
    website_url: "https://glpv.example.com",
    city: "Cleveland",
    state_province: "OH",
    country: "United States",
    headquarters_location: "Cleveland, OH",
    primary_business_type: "Pressure Vessel / Boiler Manufacturer",
    company_description: "ASME Section VIII pressure vessels and heat exchangers up to 400 tons.",
    ai_summary:
      "Great Lakes Pressure Vessels holds ASME U, U2, and R stamps, building custom vessels and shell-and-tube heat exchangers up to 400 tons for refining and chemical processing. NDE performed in-house including RT and UT.",
    services: j(["ASME vessel fabrication", "Heat exchanger manufacturing", "Code repair (R stamp)"]),
    capabilities: j(["Heavy rolling to 4.5 in plate", "Post-weld heat treatment", "In-house NDE"]),
    certifications_held: j(["ASME U Stamp", "ASME U2 Stamp", "NBIC R Stamp"]),
    industries_served: j(["Refining", "Chemical processing", "Power"]),
    equipment_list: j(["Davi MCB 3045 plate roll", "PWHT furnace 14x14x40 ft"]),
    contact_email: "sales@glpv.example.com",
    contact_phone: "(216) 555-0119",
    year_established: "1963",
    employee_count: "220",
    facility_size_sqft: "310000",
    logo_url: null,
    enterprise_tier: 1,
    enterprise_suitability_score: 95,
    completeness_status: "verified",
    confidence_level: "high",
    lifecycle_stage: "fully_built",
    data_source: "ASME+ThomasNet",
    last_updated: "2026-07-03 15:45:00",
  },
  {
    id: 4,
    company_name: "Alpine Sheet Metal Works",
    website_url: "https://alpinesheetmetal.example.com",
    city: "Denver",
    state_province: "CO",
    country: "United States",
    headquarters_location: "Denver, CO",
    primary_business_type: "Sheet Metal Fabricator",
    company_description: "Precision sheet metal fabrication with fiber laser cutting and powder coating.",
    ai_summary:
      "Alpine Sheet Metal Works provides turnkey precision sheet metal — fiber laser cutting to 1 in steel, CNC press brakes, hardware insertion, welding, and in-house powder coating — for electronics enclosures and medical carts.",
    services: j(["Laser cutting", "CNC forming", "Powder coating", "Welding & assembly"]),
    capabilities: j(["Fiber laser 12kW", "Robotic press brake", "Kitting & JIT delivery"]),
    certifications_held: j(["ISO 9001:2015"]),
    industries_served: j(["Electronics", "Medical devices", "Telecom"]),
    equipment_list: j(["Trumpf TruLaser 5030", "Amada HG 1003 ATC"]),
    contact_email: "info@alpinesheetmetal.example.com",
    contact_phone: "(303) 555-0135",
    year_established: "1996",
    employee_count: "85",
    facility_size_sqft: "95000",
    logo_url: null,
    enterprise_tier: 2,
    enterprise_suitability_score: 74,
    completeness_status: "verified",
    confidence_level: "medium",
    lifecycle_stage: "discovered",
    data_source: "IndustryNet",
    last_updated: "2026-06-20 11:15:00",
  },
  {
    id: 5,
    company_name: "Northshore Welding & Fabrication",
    website_url: "https://northshoreweld.example.com",
    city: "Duluth",
    state_province: "MN",
    country: "United States",
    headquarters_location: "Duluth, MN",
    primary_business_type: "Fabricator",
    company_description: "AWS-certified custom welding shop for mining and marine equipment repair.",
    ai_summary:
      "Northshore Welding & Fabrication is an AWS-certified job shop serving mining, marine, and heavy equipment customers on the Great Lakes with mobile welding crews and a 30,000 sq ft repair facility.",
    services: j(["Custom welding", "Equipment repair", "Mobile welding"]),
    capabilities: j(["FCAW", "GTAW", "Hardfacing"]),
    certifications_held: j(["AWS D1.1", "AWS D15.1"]),
    industries_served: j(["Mining", "Marine", "Heavy equipment"]),
    equipment_list: j(["Miller PipeWorx 400", "100-ton crane bay"]),
    contact_email: "shop@northshoreweld.example.com",
    contact_phone: "(218) 555-0163",
    year_established: "2008",
    employee_count: "32",
    facility_size_sqft: "30000",
    logo_url: null,
    enterprise_tier: 2,
    enterprise_suitability_score: 61,
    completeness_status: "verified",
    confidence_level: "medium",
    lifecycle_stage: "discovered",
    data_source: "DuckDuckGoDiscovery",
    last_updated: "2026-06-14 08:00:00",
  },
  {
    id: 6,
    company_name: "Officine Meccaniche Bergamo S.r.l.",
    website_url: "https://ombergamo.example.com",
    city: "Bergamo",
    state_province: "Lombardy",
    country: "Italy",
    headquarters_location: "Bergamo, Italy",
    primary_business_type: "Industrial Machinery Manufacturer",
    company_description: "Italian manufacturer of custom rolling mill equipment and heavy gearboxes.",
    ai_summary:
      "Officine Meccaniche Bergamo designs and builds custom rolling mill stands, heavy industrial gearboxes, and turnkey material handling lines, exporting to steel producers across Europe, the Middle East, and North America since 1954.",
    services: j(["Custom machinery design", "Heavy machining", "Gearbox manufacturing"]),
    capabilities: j(["Machining to 12m", "Load testing to 500kW", "On-site commissioning"]),
    certifications_held: j(["ISO 9001:2015", "CE Marking"]),
    industries_served: j(["Steel production", "Mining", "Cement"]),
    equipment_list: j(["Pama Speedram 3000", "Ingersoll gantry mill"]),
    contact_email: "export@ombergamo.example.com",
    contact_phone: "+39 035 555 0122",
    year_established: "1954",
    employee_count: "140",
    facility_size_sqft: "180000",
    logo_url: null,
    enterprise_tier: 2,
    enterprise_suitability_score: 79,
    completeness_status: "verified",
    confidence_level: "medium",
    lifecycle_stage: "discovered",
    data_source: "Wikidata+OpenCorporates",
    last_updated: "2026-06-25 17:20:00",
  },
];

export const MOCK_STATS = {
  totalVendors: 85110,
  verifiedVendors: 11676,
  tier1Vendors: 1172,
  countries: 60,
  sources: 14,
  withLogos: 6633,
};
