import type { Metadata } from "next";
import Link from "next/link";
import { Reveal } from "@/components/reveal";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How AVLpoint collects, uses, and protects data — including your rights under CCPA and GDPR.",
};

function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) {
  return (
    <Reveal>
      <section className="card p-6 sm:p-7">
        <h2 className="mb-3 font-display text-lg font-semibold text-fg">
          <span className="mr-3 font-mono text-sm text-arc">{n}</span>
          {title}
        </h2>
        <div className="space-y-3 text-sm leading-relaxed text-fg-secondary">{children}</div>
      </section>
    </Reveal>
  );
}

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6">
      <div className="anim-fade-up mb-10 text-center">
        <p className="mb-3 font-mono text-xs font-medium uppercase tracking-[0.2em] text-arc">Legal</p>
        <h1 className="font-display text-3xl font-bold tracking-tight text-fg sm:text-4xl">
          Privacy Policy
        </h1>
        <p className="mt-3 font-mono text-xs text-fg-muted">Effective July 2026 · avlpoint.com</p>
      </div>

      <div className="space-y-5">
        <Section n="01" title="What's in the vendor database">
          <p>
            AVLpoint indexes <strong className="text-fg">company-level</strong> information about
            industrial vendors: company name, capabilities, certifications, location, company
            phone, and website — compiled from public directories, certification registries,
            government open data, and vendors&apos; own websites. Every field carries provenance
            recording where it came from.
          </p>
          <p>
            We deliberately minimize <strong className="text-fg">person-level</strong> data (named
            individuals&apos; direct emails or phone numbers). Where it exists, it is suppressed
            from public display and gated behind logged, terms-bound accounts.
          </p>
        </Section>

        <Section n="02" title="Your rights (CCPA, GDPR, and everywhere else)">
          <p>
            If you are a California resident, you may request deletion, correction, and opt-out of
            sale or sharing of your personal information — including work contact details. If you
            are in the EU/EEA/UK, our lawful basis for processing public B2B data is legitimate
            interest, and you may object, request access, correction, or erasure at any time.
          </p>
          <p>
            We honor all of these through one place:{" "}
            <Link href="/do-not-sell" className="text-arc hover:underline">
              the removal &amp; do-not-sell request page
            </Link>
            . Requests are confirmed by email and processed within 30 days.
          </p>
        </Section>

        <Section n="03" title="Account data">
          <p>
            When you register we store your email, name, hashed password (bcrypt), and role. We use
            it to run your account, saved shortlists, and searches. We do not sell account data.
            Session cookies are httpOnly and used solely for authentication.
          </p>
        </Section>

        <Section n="04" title="Claimed profiles are consented data">
          <p>
            When a vendor claims and enriches their own profile, that submission is first-party,
            consented data. Claim owners can edit or remove their enrichments at any time from
            their dashboard, or by contacting us.
          </p>
        </Section>

        <Section n="05" title="AI processing">
          <p>
            Search ranking and recommendation explanations are generated by Claude running against
            our own database on our own infrastructure. Queries and candidate records are sent to
            the model to produce rankings; they are not used to train models. Enterprise sandbox
            data (when available) is isolated per organization and never appears in another
            organization&apos;s results.
          </p>
        </Section>

        <Section n="06" title="Retention and security">
          <p>
            Vendor records persist while relevant, with corrections and removals honored as
            described above. Removal requests and their outcomes are retained as compliance
            evidence. We use encrypted transport, hashed credentials, access-tiered gating, and
            audit logging on sensitive operations.
          </p>
        </Section>

        <Section n="07" title="Contact">
          <p>
            Privacy questions or requests: <span className="font-mono">privacy@avlpoint.com</span>,
            or use the{" "}
            <Link href="/do-not-sell" className="text-arc hover:underline">
              request form
            </Link>
            . See also our{" "}
            <Link href="/terms" className="text-arc hover:underline">
              Terms of Service
            </Link>
            .
          </p>
        </Section>
      </div>
    </div>
  );
}
